version: '3'
networks:
    spring-boot-network: null
services: 
    widget-db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root1234
            MYSQL_USER: carjam
            MYSQL_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: widget
        ports: #local machine: container
            - "60330:3306"
        expose:
            - "3306"
            - "60330"
        volumes:
            #Mapping mysql folder to a volume
            - widget-db:/var/lib/mysql:delegated
            - ./src/main/resources/db/initialize_db.sql:/docker-entrypoint-initdb.d/0_init.sql
        networks: 
            spring-boot-network:
                aliases: 
                - widget-db.dev
    app:
        restart: on-failure:3 
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - '8080:8080'
        expose:
          - "8080" 
        volumes:
          - ../.:/opt/project:delegated
          - mavencache:/root/.m2
        networks:
            spring-boot-network:
                aliases: 
                    - app.dev
        depends_on: 
            - widget-db
        environment: 
            MAVEN_OPTS: -Xmx1024m
            DATABASE_HOST: widget-db
            DATABASE_USER: carjam
            DATABASE_PASSWORD: password
            DATABASE_NAME: widget
            DATABASE_PORT: 3306
            SPRING_PROFILES_ACTIVE: dev
            LOG_LEVEL: INFO
        #working_dir: /opt/project
        command: 'mvn spring-boot:run'
    
volumes:
    widget-db: null
    mavencache: null
