version: '3'
networks:
    spring-boot-network: null
services: 
    widget-db:
        image: mysql:8.0
        restart: always
        env_file:
          - .env
        ports: #local machine: container
            - "60330:3306"
        expose:
            - "3306"
            - "60330"
        volumes:
            #Mapping mysql folder to a volume
            - widget-db:/var/lib/mysql:delegated
            - ./src/main/resources/db/initialize_db.sql:/docker-entrypoint-initdb.d/0_init.sql
        networks: 
            spring-boot-network:
                aliases: 
                - widget-db.dev
    app:
        restart: on-failure:3 
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - '8080:8080'
        expose:
          - "8080" 
        volumes:
          - ../.:/opt/project:delegated
          - mavencache:/root/.m2
        networks:
            spring-boot-network:
                aliases: 
                    - app.dev
        depends_on: 
            - widget-db
        env_file:
          - .env
        #working_dir: /opt/project
        command: 'mvn spring-boot:run'
    
volumes:
    widget-db: null
    mavencache: null
